name: deploy

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda jika berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Sesuaikan dengan versi Python Anda

      - name: Install dependencies
        run: |
          pip install jupyter-book ghp-import

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _build/html
